# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xff2d6ab33e135daa;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports

# Type definition
struct Point {
   y @0: Float64;
   x @1: Float64;
   z @2: Float64;
   
}
