# Generated by ./generate_schemas.py. This file should not be modified by hand.
@0xe2bf82e060f5e25e;

# Namespace setup
using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("gams::types");

# Capnfile Imports
using import "Quaternion.capnp".Quaternion;
using import "Point.capnp".Point;

# Type definition
struct Pose {
   position @0: Point;
   orientation @1: Quaternion;
   
}
